Update semgrep.yml

diff --git a/.github/workflows/semgrep.yml b/.github/workflows/semgrep.yml
--- a/.github/workflows/semgrep.yml
+++ b/.github/workflows/semgrep.yml
@@ -1,43 +1,56 @@
+name: Semgrep
+
 on:
   workflow_dispatch: {}
   pull_request: {}
   push:
     branches:
-    - release
-    - master
-    - develop
+      - release
+      - master
+      - develop
     paths:
-    - .github/workflows/semgrep.yml
+      - .github/workflows/semgrep.yml
   schedule:
-  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
-  - cron: 25 3 * * *
-name: Semgrep
+    # Run daily at 03:25 UTC
+    - cron: "25 3 * * *"
+
 jobs:
   semgrep:
     name: semgrep/ci
     runs-on: ubuntu-20.04
     env:
       SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
-    container:
-      image: returntocorp/semgrep
-    steps:
-    - uses: actions/checkout@v3
-    - name: Run Semgrep scan
-      id: semgrep
-      run: semgrep --config auto --json . > semgrep_results.json
+      DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECT_DOJO_API_KEY }}
+      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
+      PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
+      ENGAGEMENT_NAME: ${{ secrets.ENGAGEMENT_NAME }}
 
-    - name: Upload Semgrep report to DefectDojo
-      env:
-        DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECT_DOJO_API_KEY }}
-        DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
-        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
-        ENGAGEMENT_NAME: ${{ secrets.ENGAGEMENT_NAME }}
-      run: |
-        pip install requests
-        python .github/workflows/upload_semgrep_to_defectdojo.py \
-          --host $DEFECTDOJO_URL \
-          --token "1b9c5ac045cfec60f3b508e969a6d3b7d3f52247" \
-          --product $PRODUCT_NAME \
-          --engagement $ENGAGEMENT_NAME \
-          --report report.json \
-          --is_new_import
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Run Semgrep scan
+        id: semgrep
+        run: semgrep --config auto --json . > semgrep_results.json
+
+      - name: Check if report.json exists
+        run: |
+          if [ ! -f "semgrep_results.json" ]; then
+            echo "semgrep_results.json not found, exiting."
+            exit 1
+          fi
+
+      - name: Print current directory
+        run: |
+          pwd
+
+      - name: Upload Semgrep report to DefectDojo
+        run: |
+          pip install requests
+          python .github/workflows/upload_semgrep_to_defectdojo.py \
+            --host $DEFECTDOJO_URL \
+            --token "1b9c5ac045cfec60f3b508e969a6d3b7d3f52247" \
+            --product $PRODUCT_NAME \
+            --engagement $ENGAGEMENT_NAME \
+            --report semgrep_results.json \
+            --is_new_import
